In [88]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
from sklearn.metrics import make_scorer

In [75]:
abalone = pd.read_csv('abalone.csv')
abalone

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [76]:
abalone['Sex'] = abalone['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))
abalone.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,-1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,1,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [77]:
X_train, Y_train = abalone[abalone.columns[:-1]], abalone['Rings']

In [78]:
kf = KFold(n_splits=5,shuffle = True, random_state = 1)
kf

KFold(n_splits=5, random_state=1, shuffle=True)

In [102]:
a = make_scorer(r2_score)
kol_vo = []

for i in range(1,51):
    clf = RandomForestRegressor(n_estimators=i, random_state=1)
    if (sum(cross_val_score(clf, X_train, Y_train, cv=kf, scoring = a)/5)) > 0.52:
            kol_vo.append(i)

In [115]:
kol_vo[0]+1

22

In [104]:
a = make_scorer(r2_score)
kol = []

for i in range(1,51):
    clf = RandomForestRegressor(n_estimators=i, random_state=1)
    kol.append(sum(cross_val_score(clf, X_train, Y_train, cv=kf,scoring = a)/5))

In [106]:
kol

[0.10967482068860261,
 0.3413000096365689,
 0.40643382906612907,
 0.44477458575369117,
 0.46503241426823605,
 0.47139595825898917,
 0.4766658451893486,
 0.48293483942246307,
 0.4894370162945041,
 0.4954085552428177,
 0.4944111155773556,
 0.49902817866563326,
 0.5030578549564464,
 0.5073168234618861,
 0.5091809969556578,
 0.5114105314179662,
 0.5148917747729636,
 0.5172203573170133,
 0.5198293095329432,
 0.5194843503377499,
 0.520529096463528,
 0.5208044230080824,
 0.521742855685855,
 0.5231059969795335,
 0.5232486470488317,
 0.5243076139284634,
 0.5246393588459404,
 0.5256557724971402,
 0.5265556293057552,
 0.5270858715838138,
 0.5276420438225102,
 0.5289244806388986,
 0.5301073722643779,
 0.5299613734264366,
 0.5298209779129148,
 0.529910050667947,
 0.5294320415136227,
 0.5294715388671245,
 0.529515898349607,
 0.529470358037813,
 0.5298087685207094,
 0.5300433306143383,
 0.5299135764090978,
 0.5296814957917958,
 0.528908112349864,
 0.5290083070325597,
 0.5291786571646145,
 0.5300509396315632,
 0.530813058616495,
 0.5309509147417047]